import Navigation from "../components/navigation";

export const metadata = {
  title: {
    default: "Default",
    template: "%s | NextJs",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
